import { cpSync, existsSync, lstatSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { assertUnitbobPath } from './artifactPath.ts';
import { BDD_RUN_ARTIFACTS } from '../runner/bdd.ts';
import type { SuiteArtifact } from '../wire.ts';

// The behavioral suite lives under its own root: the main `.feature` plus its
// step definitions and any helper files, all under `.unitbob/behavioral/`
// (spec 32). Nothing here is ever written into the project's own `spec/`,
// `features/`, or `tests/`. Like the structural flow, the host LLM writes and
// runs the suite to green before upload; the connector materializes the stored
// blob only so `check` can execute it locally.
export const BEHAVIORAL_DIR = '.unitbob/behavioral';
export const BEHAVIORAL_WORLD_PATH = `${BEHAVIORAL_DIR}/step_definitions/00_unitbob_world.rb`;
const BEHAVIORAL_WORLD_JS_PATH = `${BEHAVIORAL_DIR}/step_definitions/00_unitbob_world.js`;
// A level above "step_definitions/", and deliberately. pytest loads every
// conftest.py from the rootdir down to the directory it collects, so this one is
// loaded — and the host's own "step_definitions/conftest.py", which the step
// loading rules already promise them as the home for shared fixtures, stays
// theirs. Claiming that filename here would take it away.
const BEHAVIORAL_WORLD_PY_PATH = `${BEHAVIORAL_DIR}/conftest.py`;

// The Ruby/Cucumber harness is connector-owned. Host agents own business steps;
// this file owns only the stable Rails integration seam they build on.
export const BEHAVIORAL_WORLD = `# Generated by Unitbob. DO NOT EDIT: suite materialization restores this file.
repo_root = ENV.fetch('UNITBOB_REPO_ROOT')
ENV['RAILS_ENV'] ||= 'test'
require File.join(repo_root, 'config', 'environment')
require 'action_dispatch/testing/integration'
require 'rspec/expectations'
require 'rspec/mocks'

module UnitbobWorld
  include RSpec::Matchers
  include RSpec::Mocks::ExampleMethods

  attr_reader :unitbob_session

  def unitbob_get(path, **options)
    unitbob_session.get(path, **options)
  end

  def unitbob_post(path, **options)
    unitbob_session.post(path, **options)
  end

  def unitbob_patch(path, **options)
    unitbob_session.patch(path, **options)
  end

  def unitbob_put(path, **options)
    unitbob_session.put(path, **options)
  end

  def unitbob_delete(path, **options)
    unitbob_session.delete(path, **options)
  end

  def unitbob_expect_status(status)
    unitbob_session.assert_response(status)
  end

  def unitbob_expect_redirect_to(location)
    unitbob_session.assert_redirected_to(location)
  end
end

World(UnitbobWorld)

# Cucumber loads neither spec/rails_helper.rb nor spec/support/**, so every
# switch this project's RSpec setup throws is still off here. Nothing said so:
# the behavioral branch just behaved differently from the structural one, and
# outgoing HTTP went to the real network while the structural branch had it
# blocked (spec 35-1).
#
# Only what is the same in every Rails application belongs below. Anything that
# depends on *this* application — signing in, factories, reading props, stubbing
# a payment provider — stays in host-owned shared steps, where it always was.
#
# And not one step definition, here or anywhere in this file. That is a rule with
# a mechanical reason: Cucumber loads every step file in the bundle into a single
# flat namespace, so a step defined here would not merely risk colliding with a
# worker's step — it would collide, and the run would stop on an ambiguous match
# rather than fail with something a reader can act on.
begin
  require 'webmock/cucumber'
  # Localhost stays reachable on purpose: a suite that talks to a local search or
  # storage service is not the leak this closes, and blocking it would break runs
  # that were never going out of the machine.
  WebMock.disable_net_connect!(allow_localhost: true)
rescue LoadError
  warn '[unitbob] webmock could not be loaded: outgoing HTTP from this suite reaches the real network.'
end

if defined?(Sidekiq)
  begin
    require 'sidekiq/testing'
    Sidekiq::Testing.fake!
  rescue LoadError
    warn '[unitbob] sidekiq/testing could not be loaded: Sidekiq jobs in this suite are not in fake mode.'
  end
end

ActiveJob::Base.queue_adapter = :test if defined?(ActiveJob::Base)

# The host the integration session already uses, so URL helpers agree with the
# requests the steps make instead of raising for a missing default.
Rails.application.routes.default_url_options[:host] ||= 'www.example.com'

Before do
  @unitbob_time_zone = Time.zone
  @unitbob_locale = I18n.locale
  @unitbob_connection = ActiveRecord::Base.connection
  @unitbob_connection.begin_transaction(joinable: false)
  RSpec::Mocks.setup

  @unitbob_session = ActionDispatch::Integration::Session.new(Rails.application)
  @unitbob_session.singleton_class.class_eval { attr_accessor :assertions }
  @unitbob_session.assertions = 0
end

After do
  mock_error = nil
  begin
    RSpec::Mocks.verify
  rescue Exception => error # rubocop:disable Lint/RescueException
    mock_error = error
  ensure
    RSpec::Mocks.teardown
    @unitbob_connection.rollback_transaction if @unitbob_connection&.transaction_open?
    Time.zone = @unitbob_time_zone
    I18n.locale = @unitbob_locale
  end
  raise mock_error if mock_error
end
`;

// The JS/TS peer of the file above. cucumber-js reads no test bootstrap of its
// own either — and the connector's explicit `--require` switches off even its
// own `features/support/` loading — so the branch had the same silence Ruby did.
//
// There is no cross-project equivalent of "Sidekiq in fake mode": a JavaScript
// project has no one job runner. What is the same everywhere is the network, and
// that is what this file settles.
const BEHAVIORAL_WORLD_JS = `// Generated by Unitbob. DO NOT EDIT: suite materialization restores this file.
'use strict';

// cucumber-js loads none of this project's own test bootstrap — not its Vitest
// setup files, and not \`features/support/\`, which the connector's explicit
// \`--require\` switches off. Whatever your test setup switches on is still off
// here, and on one Rails run the same silence sent live HTTP to the real network
// while the structural peer had it blocked (spec 35-1).
//
// Only what is the same in every JavaScript project belongs below. Anything that
// depends on *this* application — signing in, fixtures, seeding — stays in
// host-owned shared steps, where it always was.
//
// And not one step definition, here or anywhere in this file. That is a rule with
// a mechanical reason: cucumber-js registers every step in the bundle into a
// single flat namespace, so a step defined here would not merely risk colliding
// with a worker's step — it would collide, and the run would stop on an ambiguous
// match rather than fail with something a reader can act on.
const net = require('node:net');

// Localhost stays reachable on purpose: a suite that talks to a local database,
// search or storage service is not the leak this closes, and blocking it would
// break runs that were never leaving the machine.
function unitbobLeavesThisMachine(host) {
  const name = String(host).replace(/^\\[|\\]$/g, '');
  return !(name === 'localhost' || name === '::1' || name === '0.0.0.0' || name.startsWith('127.'));
}

// Guarded at the socket, not at \`http.request\`: Node's own \`fetch\` opens its
// connections below that layer, so a guard one level up would have let the most
// modern way to call out be the one way that still worked. Mocking libraries
// (nock, msw) intercept above this and are unaffected.
// \`Socket.prototype.connect\` is called in more shapes than its documentation
// shows: \`(options)\`, \`(path)\`, \`(port, host)\`, and — from \`net.connect()\` and
// therefore from Node's own \`fetch\` — an already normalized \`[options, callback]\`
// array. Missing that last shape is not a narrower guard, it is no guard at all:
// the options land where a callback was expected, the host reads as undefined,
// and every outbound call is waved through.
function unitbobTarget(args) {
  const first = Array.isArray(args[0]) ? args[0][0] : args[0];
  // A unix socket path is not a network address at all.
  if (typeof first === 'string') return { path: first };
  if (first !== null && typeof first === 'object') return { path: first.path, host: first.host };
  return { host: typeof args[1] === 'string' ? args[1] : undefined };
}

const unitbobConnect = net.Socket.prototype.connect;
net.Socket.prototype.connect = function unitbobGuardedConnect(...args) {
  const { path, host } = unitbobTarget(args);

  if (!path && unitbobLeavesThisMachine(host === undefined ? 'localhost' : host)) {
    throw new Error(
      '[unitbob] Refused a connection to ' + host + ': this suite must not reach the network. ' +
      'Stub the boundary in your step definitions instead.',
    );
  }
  return unitbobConnect.apply(this, args);
};
`;

// The Python peer. pytest reads the connector's own ini through \`-c\`, so the
// project's pytest settings do not apply, and only the conftest.py files on the
// path from the repository root down to the collected directory are loaded —
// which is to say a project's \`tests/conftest.py\` fixtures are not here either.
const BEHAVIORAL_WORLD_PY = `# Generated by Unitbob. DO NOT EDIT: suite materialization restores this file.
"""Connector-owned harness for the Unitbob behavioral suite.

pytest runs here against the connector's own config ("-c"), so this project's
pytest settings do not apply, and the only conftest.py files loaded are those on
the path from the repository root down to "step_definitions/" — a
"tests/conftest.py" is not one of them. Whatever your own test setup switches
on is therefore still off, and on one Rails run that same silence sent live HTTP
to the real network while the structural peer had it blocked (spec 35-1).

Only what is the same in every Python project belongs here. Anything that depends
on *this* application — signing in, factories, seeding — stays in host-owned
shared steps and in your own "step_definitions/conftest.py", which this file
deliberately does not claim.

No step definitions live here, on purpose: step definitions belong to the workers
that own their capability, and a shared one would collide with theirs.
"""
import socket

_UNITBOB_LOCAL = ("localhost", "::1", "0.0.0.0", "")


def _unitbob_leaves_this_machine(address):
    # A unix socket path is a string, not an address tuple, and is not a network
    # address at all.
    if not isinstance(address, tuple) or not address:
        return False
    host = str(address[0]).strip("[]")
    # Localhost stays reachable on purpose: a suite that talks to a local
    # database, search or storage service is not the leak this closes, and
    # blocking it would break runs that were never leaving the machine.
    return not (host in _UNITBOB_LOCAL or host.startswith("127."))


def _unitbob_refuse(address):
    return OSError(
        "[unitbob] Refused a connection to %s: this suite must not reach the "
        "network. Stub the boundary in your step definitions instead." % (address,)
    )


# Guarded at the socket, so it holds for requests, urllib3, httpx, aiohttp and
# anything else, rather than for the one HTTP client this file happened to know
# about. Mocking libraries (responses, respx) intercept above this and are
# unaffected.
_unitbob_connect = socket.socket.connect
_unitbob_connect_ex = socket.socket.connect_ex


def _unitbob_guarded_connect(self, address):
    if _unitbob_leaves_this_machine(address):
        raise _unitbob_refuse(address)
    return _unitbob_connect(self, address)


def _unitbob_guarded_connect_ex(self, address):
    if _unitbob_leaves_this_machine(address):
        raise _unitbob_refuse(address)
    return _unitbob_connect_ex(self, address)


socket.socket.connect = _unitbob_guarded_connect
socket.socket.connect_ex = _unitbob_guarded_connect_ex
`;

export interface BehavioralWorld {
  path: string;
  content: string;
}

// One connector-owned harness per BDD runner, or nothing for a runner that has
// none. Kept as one table so a fourth runner cannot be added with a step-loading
// rule and no harness — the two halves of "what this branch runs inside".
const BEHAVIORAL_WORLDS: Readonly<Record<string, BehavioralWorld>> = {
  cucumber: { path: BEHAVIORAL_WORLD_PATH, content: BEHAVIORAL_WORLD },
  'cucumber-js': { path: BEHAVIORAL_WORLD_JS_PATH, content: BEHAVIORAL_WORLD_JS },
  'pytest-bdd': { path: BEHAVIORAL_WORLD_PY_PATH, content: BEHAVIORAL_WORLD_PY },
};

export function behavioralWorldFor(runner: string): BehavioralWorld | undefined {
  return BEHAVIORAL_WORLDS[runner];
}

export function materializeBehavioralWorld(projectRoot: string, runner = 'cucumber'): string | null {
  const world = behavioralWorldFor(runner);
  if (!world) return null;

  const worldPath = join(projectRoot, world.path);
  mkdirSync(dirname(worldPath), { recursive: true });
  writeFileSync(worldPath, world.content);
  return worldPath;
}

// Write a behavioral artifact envelope (main file + support files) under the
// behavioral root, after checking every path is safe. Stale suite artifacts are
// removed while the separately provisioned runner environment is preserved.
// Returns the absolute path of the materialized main file.
export function materializeBehavioral(
  projectRoot: string,
  artifact: SuiteArtifact,
  runner: string,
): { mainPath: string } {
  const files = [artifact, ...(artifact.support_files ?? [])];
  for (const file of files) assertUnitbobPath(file.path, BEHAVIORAL_DIR);
  const world = behavioralWorldFor(runner);
  if (world && files.some((file) => file.path === world.path)) {
    throw new Error(`${world.path} is the connector-owned World and cannot be supplied by the host artifact.`);
  }

  const behavioralRoot = join(projectRoot, BEHAVIORAL_DIR);
  const runnerEntries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;
  mkdirSync(behavioralRoot, { recursive: true });
  for (const entry of readdirSync(behavioralRoot)) {
    if (!runnerEntries.has(entry)) {
      rmSync(join(behavioralRoot, entry), { recursive: true, force: true });
    }
  }

  let mainPath = '';
  for (const file of files) {
    const dest = join(projectRoot, file.path);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, file.content);
    if (file === artifact) mainPath = dest;
  }

  materializeBehavioralWorld(projectRoot, runner);

  return { mainPath };
}

// Everything under the behavioral root that the next materialization will
// delete: it wipes every top-level entry outside the runner environment and
// writes back only the files the answer listed, so a step file the answer forgot
// is gone and its steps come back undefined — a harness break reported far from
// its cause. One file per capability makes forgetting one much easier than a
// single file for the whole product ever did.
//
// The whole root is walked, not just the directories the answer happens to use:
// the file most likely to be forgotten is the one in a directory the answer
// never mentions — `features/support/env.rb` is exactly that shape.
export function filesLostOnMaterialize(projectRoot: string, artifact: SuiteArtifact, runner: string): string[] {
  const behavioralRoot = join(projectRoot, BEHAVIORAL_DIR);
  if (!existsSync(behavioralRoot)) return [];

  const connectorWorld = behavioralWorldFor(runner);
  const listed = new Set([
    artifact.path,
    ...(artifact.support_files ?? []).map((file) => file.path),
    ...(connectorWorld ? [connectorWorld.path] : []),
  ]);
  const runnerEntries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;

  return readdirSync(behavioralRoot)
    .filter((entry) => !runnerEntries.has(entry) && !CONNECTOR_RUN_ARTIFACTS.has(entry))
    .flatMap((entry) => filesUnder(projectRoot, `${BEHAVIORAL_DIR}/${entry}`))
    .filter((path) => !listed.has(path) && !isRuntimeByProduct(path))
    .sort();
}

// The real files under `relative`. Symlinks are not followed: materialization
// removes the link, not what it points at, and naming the target here would read
// as a warning about a file that was never in danger.
function filesUnder(projectRoot: string, relative: string): string[] {
  const stats = lstatSync(join(projectRoot, relative));
  if (stats.isFile()) return [relative];
  if (!stats.isDirectory()) return [];

  return readdirSync(join(projectRoot, relative)).flatMap((entry) => filesUnder(projectRoot, `${relative}/${entry}`));
}

// What the branch's own run leaves behind while it runs: Python's byte-code
// cache beside every step file, the SQLite database the World opens at start
// and its journal. Nobody wrote them, the next run makes them again, and the
// answer could not list them if it tried. On the bench, 2026-09-11, the review
// warning named fourteen `.pyc` files on microblog and the World's own database
// on soul as things "running it will delete" — the same way the connector's
// report files used to be named, and for the same cost: a warning that fires on
// every review is a warning nobody reads when a step file really is forgotten.
//
// Matched anywhere in the path, not only at the top: `__pycache__` sits inside
// `step_definitions/`, where the top-level filter above never looks.
const RUNTIME_BY_PRODUCT_DIRS: ReadonlySet<string> = new Set(['__pycache__', '.pytest_cache']);
const RUNTIME_BY_PRODUCT_FILE = /\.(pyc|sqlite|sqlite3|db|db-shm|db-wal|db-journal)$/;

function isRuntimeByProduct(relativePath: string): boolean {
  const parts = relativePath.split('/');
  return parts.some((part) => RUNTIME_BY_PRODUCT_DIRS.has(part)) || RUNTIME_BY_PRODUCT_FILE.test(parts[parts.length - 1]);
}

export function copyBehavioralRunnerEnvironment(
  sourceRoot: string,
  targetRoot: string,
  runner: string,
): void {
  const entries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;
  for (const entry of entries) {
    const source = join(sourceRoot, BEHAVIORAL_DIR, entry);
    if (!existsSync(source)) continue;

    const target = join(targetRoot, BEHAVIORAL_DIR, entry);
    mkdirSync(dirname(target), { recursive: true });
    cpSync(source, target, { recursive: true });
  }
}

// Written into the behavioral root by the connector's own BDD run: the machine
// report and the pytest-bdd harness it drives the run with. They are regenerated
// by the next run, so materialization is right to clear them — but warning about
// them names the connector's own files as the user's loss. It made the warning
// fire on every single review, which is how a real forgotten step file learns to
// look like noise. Taken from the runner that writes them, never re-typed here.
const CONNECTOR_RUN_ARTIFACTS: ReadonlySet<string> = new Set(BDD_RUN_ARTIFACTS);

const EMPTY_ENTRIES = new Set<string>();

// What under the behavioral root is an *installed environment* rather than
// generated text. Exported since spec 36: when the place a run happens in
// changes, exactly these entries are thrown away so they can be installed again,
// and the generated suite sitting beside them is left untouched.
export const RUNNER_ENVIRONMENT_ENTRIES: Record<string, ReadonlySet<string>> = {
  cucumber: new Set(['.bundle', 'Gemfile', 'Gemfile.lock']),
  'cucumber-js': new Set(['node_modules', 'package.json', 'package-lock.json', 'pnpm-lock.yaml', 'yarn.lock']),
  'pytest-bdd': new Set(['.venv']),
};
