import { cpSync, existsSync, lstatSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { assertUnitbobPath } from './artifactPath.ts';
import { BDD_RUN_ARTIFACTS } from '../runner/bdd.ts';
import type { SuiteArtifact } from '../wire.ts';

// The behavioral suite lives under its own root: the main `.feature` plus its
// step definitions and any helper files, all under `.unitbob/behavioral/`
// (spec 32). Nothing here is ever written into the project's own `spec/`,
// `features/`, or `tests/`. Like the structural flow, the host LLM writes and
// runs the suite to green before upload; the connector materializes the stored
// blob only so `check` can execute it locally.
export const BEHAVIORAL_DIR = '.unitbob/behavioral';
export const BEHAVIORAL_WORLD_PATH = `${BEHAVIORAL_DIR}/step_definitions/00_unitbob_world.rb`;

// The Ruby/Cucumber harness is connector-owned. Host agents own business steps;
// this file owns only the stable Rails integration seam they build on.
export const BEHAVIORAL_WORLD = `# Generated by Unitbob. DO NOT EDIT: suite materialization restores this file.
repo_root = ENV.fetch('UNITBOB_REPO_ROOT')
ENV['RAILS_ENV'] ||= 'test'
require File.join(repo_root, 'config', 'environment')
require 'action_dispatch/testing/integration'
require 'rspec/expectations'
require 'rspec/mocks'

module UnitbobWorld
  include RSpec::Matchers
  include RSpec::Mocks::ExampleMethods

  attr_reader :unitbob_session

  def unitbob_get(path, **options)
    unitbob_session.get(path, **options)
  end

  def unitbob_post(path, **options)
    unitbob_session.post(path, **options)
  end

  def unitbob_patch(path, **options)
    unitbob_session.patch(path, **options)
  end

  def unitbob_put(path, **options)
    unitbob_session.put(path, **options)
  end

  def unitbob_delete(path, **options)
    unitbob_session.delete(path, **options)
  end

  def unitbob_expect_status(status)
    unitbob_session.assert_response(status)
  end

  def unitbob_expect_redirect_to(location)
    unitbob_session.assert_redirected_to(location)
  end
end

World(UnitbobWorld)

Before do
  @unitbob_time_zone = Time.zone
  @unitbob_locale = I18n.locale
  @unitbob_connection = ActiveRecord::Base.connection
  @unitbob_connection.begin_transaction(joinable: false)
  RSpec::Mocks.setup

  @unitbob_session = ActionDispatch::Integration::Session.new(Rails.application)
  @unitbob_session.singleton_class.class_eval { attr_accessor :assertions }
  @unitbob_session.assertions = 0
end

After do
  mock_error = nil
  begin
    RSpec::Mocks.verify
  rescue Exception => error # rubocop:disable Lint/RescueException
    mock_error = error
  ensure
    RSpec::Mocks.teardown
    @unitbob_connection.rollback_transaction if @unitbob_connection&.transaction_open?
    Time.zone = @unitbob_time_zone
    I18n.locale = @unitbob_locale
  end
  raise mock_error if mock_error
end
`;

export function materializeBehavioralWorld(projectRoot: string): string {
  const worldPath = join(projectRoot, BEHAVIORAL_WORLD_PATH);
  mkdirSync(dirname(worldPath), { recursive: true });
  writeFileSync(worldPath, BEHAVIORAL_WORLD);
  return worldPath;
}

// Write a behavioral artifact envelope (main file + support files) under the
// behavioral root, after checking every path is safe. Stale suite artifacts are
// removed while the separately provisioned runner environment is preserved.
// Returns the absolute path of the materialized main file.
export function materializeBehavioral(
  projectRoot: string,
  artifact: SuiteArtifact,
  runner: string,
): { mainPath: string } {
  const files = [artifact, ...(artifact.support_files ?? [])];
  for (const file of files) assertUnitbobPath(file.path, BEHAVIORAL_DIR);
  if (files.some((file) => file.path === BEHAVIORAL_WORLD_PATH)) {
    throw new Error(`${BEHAVIORAL_WORLD_PATH} is the connector-owned World and cannot be supplied by the host artifact.`);
  }

  const behavioralRoot = join(projectRoot, BEHAVIORAL_DIR);
  const runnerEntries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;
  mkdirSync(behavioralRoot, { recursive: true });
  for (const entry of readdirSync(behavioralRoot)) {
    if (!runnerEntries.has(entry)) {
      rmSync(join(behavioralRoot, entry), { recursive: true, force: true });
    }
  }

  let mainPath = '';
  for (const file of files) {
    const dest = join(projectRoot, file.path);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, file.content);
    if (file === artifact) mainPath = dest;
  }

  if (runner === 'cucumber') {
    materializeBehavioralWorld(projectRoot);
  }

  return { mainPath };
}

// Everything under the behavioral root that the next materialization will
// delete: it wipes every top-level entry outside the runner environment and
// writes back only the files the answer listed, so a step file the answer forgot
// is gone and its steps come back undefined — a harness break reported far from
// its cause. One file per capability makes forgetting one much easier than a
// single file for the whole product ever did.
//
// The whole root is walked, not just the directories the answer happens to use:
// the file most likely to be forgotten is the one in a directory the answer
// never mentions — `features/support/env.rb` is exactly that shape.
export function filesLostOnMaterialize(projectRoot: string, artifact: SuiteArtifact, runner: string): string[] {
  const behavioralRoot = join(projectRoot, BEHAVIORAL_DIR);
  if (!existsSync(behavioralRoot)) return [];

  const listed = new Set([
    artifact.path,
    ...(artifact.support_files ?? []).map((file) => file.path),
    ...(runner === 'cucumber' ? [BEHAVIORAL_WORLD_PATH] : []),
  ]);
  const runnerEntries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;

  return readdirSync(behavioralRoot)
    .filter((entry) => !runnerEntries.has(entry) && !CONNECTOR_RUN_ARTIFACTS.has(entry))
    .flatMap((entry) => filesUnder(projectRoot, `${BEHAVIORAL_DIR}/${entry}`))
    .filter((path) => !listed.has(path))
    .sort();
}

// The real files under `relative`. Symlinks are not followed: materialization
// removes the link, not what it points at, and naming the target here would read
// as a warning about a file that was never in danger.
function filesUnder(projectRoot: string, relative: string): string[] {
  const stats = lstatSync(join(projectRoot, relative));
  if (stats.isFile()) return [relative];
  if (!stats.isDirectory()) return [];

  return readdirSync(join(projectRoot, relative)).flatMap((entry) => filesUnder(projectRoot, `${relative}/${entry}`));
}

export function copyBehavioralRunnerEnvironment(
  sourceRoot: string,
  targetRoot: string,
  runner: string,
): void {
  const entries = RUNNER_ENVIRONMENT_ENTRIES[runner] ?? EMPTY_ENTRIES;
  for (const entry of entries) {
    const source = join(sourceRoot, BEHAVIORAL_DIR, entry);
    if (!existsSync(source)) continue;

    const target = join(targetRoot, BEHAVIORAL_DIR, entry);
    mkdirSync(dirname(target), { recursive: true });
    cpSync(source, target, { recursive: true });
  }
}

// Written into the behavioral root by the connector's own BDD run: the machine
// report and the pytest-bdd harness it drives the run with. They are regenerated
// by the next run, so materialization is right to clear them — but warning about
// them names the connector's own files as the user's loss. It made the warning
// fire on every single review, which is how a real forgotten step file learns to
// look like noise. Taken from the runner that writes them, never re-typed here.
const CONNECTOR_RUN_ARTIFACTS: ReadonlySet<string> = new Set(BDD_RUN_ARTIFACTS);

const EMPTY_ENTRIES = new Set<string>();
const RUNNER_ENVIRONMENT_ENTRIES: Record<string, ReadonlySet<string>> = {
  cucumber: new Set(['.bundle', 'Gemfile', 'Gemfile.lock']),
  'cucumber-js': new Set(['node_modules', 'package.json', 'package-lock.json', 'pnpm-lock.yaml', 'yarn.lock']),
  'pytest-bdd': new Set(['.venv']),
};
