import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { runProcess, type ProcResult } from '../proc.ts';

export interface ProvisionResult {
  status: 'provisioned' | 'fixable';
  message?: string;
  checklist?: string[];
}

export interface ProvisionDeps {
  runCmd: (command: string, args: string[], options: { cwd: string; env?: Record<string, string> }) => Promise<ProcResult>;
}

const defaultDeps: ProvisionDeps = {
  runCmd: (command, args, options) =>
    runProcess(command, args, { cwd: options.cwd, timeoutMs: 120_000, env: { ...process.env, ...options.env } }),
};

export async function ensureRunner(
  projectRoot: string,
  runner: string,
  deps: ProvisionDeps = defaultDeps,
): Promise<ProvisionResult> {
  const behavioralDir = join(projectRoot, '.unitbob', 'behavioral');
  mkdirSync(behavioralDir, { recursive: true });

  switch (runner) {
    case 'cucumber':
      return provisionRuby(projectRoot, behavioralDir, deps);
    case 'cucumber-js':
      return provisionJs(projectRoot, behavioralDir, deps);
    case 'pytest-bdd':
      return provisionPython(projectRoot, behavioralDir, deps);
    default:
      return { status: 'fixable', message: `Unsupported BDD runner "${runner}".` };
  }
}

async function provisionRuby(
  projectRoot: string,
  behavioralDir: string,
  deps: ProvisionDeps,
): Promise<ProvisionResult> {
  const sidecarGemfile = join(behavioralDir, 'Gemfile');
  const sidecarContent =
    '# Sidecar Gemfile generated by Unitbob (Spec 32-1)\n' +
    'eval_gemfile File.expand_path("../../../Gemfile", __FILE__)\n' +
    'gem "cucumber", "~> 9.0", require: false\n';

  if (!existsSync(sidecarGemfile) || readFileSync(sidecarGemfile, 'utf8') !== sidecarContent) {
    writeFileSync(sidecarGemfile, sidecarContent);
  }

  const gemfileRel = '.unitbob/behavioral/Gemfile';
  const env = { BUNDLE_GEMFILE: gemfileRel };

  // Try project local bin/bundle, then bundle
  const localBundle = join(projectRoot, 'bin', 'bundle');
  const cmd = existsSync(localBundle) ? localBundle : 'bundle';
  const result = await deps.runCmd(cmd, ['install'], { cwd: projectRoot, env }).catch((err) => ({
    code: 1,
    stdout: '',
    stderr: String(err),
  }));

  if (result.code === 0) {
    return { status: 'provisioned' };
  }

  return {
    status: 'fixable',
    message: 'Bundler failed to provision Cucumber sidecar gem.',
    checklist: ['Ensure bundler is installed (`gem install bundler`) and run `bundle install` manually inside `.unitbob/behavioral/`.'],
  };
}

async function provisionPython(
  projectRoot: string,
  behavioralDir: string,
  deps: ProvisionDeps,
): Promise<ProvisionResult> {
  const venvDir = join(behavioralDir, '.venv');
  const venvPip = join(venvDir, 'bin', 'pip');
  const venvPytest = join(venvDir, 'bin', 'pytest');

  if (existsSync(venvPytest)) {
    return { status: 'provisioned' };
  }

  // Ladder: uv -> python3 -m venv --system-site-packages
  const uvResult = await deps.runCmd('uv', ['venv', venvDir, '--system-site-packages'], { cwd: projectRoot }).catch(() => ({ code: 1 }));
  let venvCreated = uvResult.code === 0;

  if (!venvCreated) {
    const venvResult = await deps
      .runCmd('python3', ['-m', 'venv', '--system-site-packages', venvDir], { cwd: projectRoot })
      .catch(() => ({ code: 1 }));
    venvCreated = venvResult.code === 0;
  }

  if (!venvCreated) {
    return {
      status: 'fixable',
      message: 'Failed to create virtual environment under .unitbob/behavioral/.venv.',
      checklist: ['Install python3-venv or uv: `python3 -m venv --help` or `pip install uv`.'],
    };
  }

  // Install pytest-bdd into the sidecar venv
  const pipResult = await deps.runCmd(venvPip, ['install', 'pytest-bdd'], { cwd: projectRoot }).catch(() => ({ code: 1 }));
  if (pipResult.code === 0 || existsSync(venvPytest)) {
    return { status: 'provisioned' };
  }

  return {
    status: 'fixable',
    message: 'Failed to install pytest-bdd into .unitbob/behavioral/.venv.',
    checklist: [`Run \`${venvPip} install pytest-bdd\` manually to provision the runner.`],
  };
}

async function provisionJs(
  projectRoot: string,
  behavioralDir: string,
  deps: ProvisionDeps,
): Promise<ProvisionResult> {
  const sidecarPkg = join(behavioralDir, 'package.json');
  const sidecarContent = JSON.stringify(
    {
      name: 'unitbob-behavioral-sidecar',
      private: true,
      devDependencies: {
        '@cucumber/cucumber': '^10.0.0',
        'ts-node': '^10.9.0',
      },
    },
    null,
    2,
  ) + '\n';

  if (!existsSync(sidecarPkg) || readFileSync(sidecarPkg, 'utf8') !== sidecarContent) {
    writeFileSync(sidecarPkg, sidecarContent);
  }

  const cucumberBin = join(behavioralDir, 'node_modules', '.bin', 'cucumber-js');
  if (existsSync(cucumberBin)) {
    return { status: 'provisioned' };
  }

  // Fallback ladder: npm -> pnpm -> yarn
  const managers = [
    { cmd: 'npm', args: ['install', '--prefix', '.unitbob/behavioral'] },
    { cmd: 'pnpm', args: ['install', '--prefix', '.unitbob/behavioral'] },
    { cmd: 'yarn', args: ['install', '--cwd', '.unitbob/behavioral'] },
  ];

  for (const mgr of managers) {
    const res = await deps.runCmd(mgr.cmd, mgr.args, { cwd: projectRoot }).catch(() => ({ code: 1 }));
    if (res.code === 0 || existsSync(cucumberBin)) {
      return { status: 'provisioned' };
    }
  }

  return {
    status: 'fixable',
    message: 'Failed to install @cucumber/cucumber sidecar dependency.',
    checklist: ['Install dependencies manually: `npm install --prefix .unitbob/behavioral`.'],
  };
}
